module.exports = {
	"total":224,
	"countries":[
		{
			"callingCode":"358",
			"iso2Code":"AX",
			"iso3Code":"ala",
			"name":"Åland Islands"
		},
		{
			"callingCode":"355",
			"iso2Code":"AL",
			"iso3Code":"alb",
			"name":"Albania"
		},
		{
			"callingCode":"213",
			"iso2Code":"DZ",
			"iso3Code":"dza",
			"name":"Algeria"
		},
		{
			"callingCode":"1",
			"iso2Code":"AS",
			"iso3Code":"asm",
			"name":"American Samoa"
		},
		{
			"callingCode":"376",
			"iso2Code":"AD",
			"iso3Code":"and",
			"name":"Andorra"
		},
		{
			"callingCode":"244",
			"iso2Code":"AO",
			"iso3Code":"ago",
			"name":"Angola"
		},
		{
			"callingCode":"264",
			"iso2Code":"AI",
			"iso3Code":"aia",
			"name":"Anguilla"
		},
		{
			"callingCode":"672",
			"iso2Code":"AQ",
			"iso3Code":"ata",
			"name":"Antarctica"
		},
		{
			"callingCode":"268",
			"iso2Code":"AG",
			"iso3Code":"atg",
			"name":"Antigua and Barbuda"
		},
		{
			"callingCode":"54",
			"iso2Code":"AR",
			"iso3Code":"arg",
			"name":"Argentina"
		},
		{
			"callingCode":"374",
			"iso2Code":"AM",
			"iso3Code":"arm",
			"name":"Armenia"
		},
		{
			"callingCode":"297",
			"iso2Code":"AW",
			"iso3Code":"abw",
			"name":"Aruba"
		},
		{
			"callingCode":"61",
			"iso2Code":"AU",
			"iso3Code":"aus",
			"name":"Australia"
		},
		{
			"callingCode":"43",
			"iso2Code":"AT",
			"iso3Code":"aut",
			"name":"Austria"
		},
		{
			"callingCode":"994",
			"iso2Code":"AZ",
			"iso3Code":"aze",
			"name":"Azerbaijan"
		},
		{
			"callingCode":"242",
			"iso2Code":"BS",
			"iso3Code":"bhs",
			"name":"Bahamas"
		},
		{
			"callingCode":"973",
			"iso2Code":"BH",
			"iso3Code":"bhr",
			"name":"Bahrain"
		},
		{
			"callingCode":"880",
			"iso2Code":"BD",
			"iso3Code":"bgd",
			"name":"Bangladesh"
		},
		{
			"callingCode":"1",
			"iso2Code":"BB",
			"iso3Code":"brb",
			"name":"Barbados"
		},
		{
			"callingCode":"375",
			"iso2Code":"BY",
			"iso3Code":"blr",
			"name":"Belarus"
		},
		{
			"callingCode":"32",
			"iso2Code":"BE",
			"iso3Code":"bel",
			"name":"Belgium"
		},
		{
			"callingCode":"501",
			"iso2Code":"BZ",
			"iso3Code":"blz",
			"name":"Belize"
		},
		{
			"callingCode":"229",
			"iso2Code":"BJ",
			"iso3Code":"ben",
			"name":"Benin"
		},
		{
			"callingCode":"1",
			"iso2Code":"BM",
			"iso3Code":"bmu",
			"name":"Bermuda"
		},
		{
			"callingCode":"975",
			"iso2Code":"BT",
			"iso3Code":"btn",
			"name":"Bhutan"
		},
		{
			"callingCode":"591",
			"iso2Code":"BO",
			"iso3Code":"bol",
			"name":"Bolivia"
		},
		{
			"callingCode":"599",
			"iso2Code":"BQ",
			"iso3Code":"bes",
			"name":"Bonaire"
		},
		{
			"callingCode":"387",
			"iso2Code":"BA",
			"iso3Code":"bih",
			"name":"Bosnia and Herzegovina"
		},
		{
			"callingCode":"267",
			"iso2Code":"BW",
			"iso3Code":"bwa",
			"name":"Botswana"
		},
		{
			"callingCode":"47",
			"iso2Code":"BV",
			"iso3Code":"bvt",
			"name":"Bouvet Island"
		},
		{
			"callingCode":"246",
			"iso2Code":"IO",
			"iso3Code":"iot",
			"name":"British Indian Ocean Territory"
		},
		{
			"callingCode":"1",
			"iso2Code":"VG",
			"iso3Code":"vgb",
			"name":"British Virgin Islands"
		},
		{
			"callingCode":"673",
			"iso2Code":"BN",
			"iso3Code":"brn",
			"name":"Brunei Darussalam"
		},
		{
			"callingCode":"359",
			"iso2Code":"BG",
			"iso3Code":"bgr",
			"name":"Bulgaria"
		},
		{
			"callingCode":"226",
			"iso2Code":"BF",
			"iso3Code":"bfa",
			"name":"Burkina Faso"
		},
		{
			"callingCode":"855",
			"iso2Code":"KH",
			"iso3Code":"khm",
			"name":"Cambodia"
		},
		{
			"callingCode":"237",
			"iso2Code":"CM",
			"iso3Code":"cmr",
			"name":"Cameroon"
		},
		{
			"callingCode":"1",
			"iso2Code":"CA",
			"iso3Code":"can",
			"name":"Canada"
		},
		{
			"callingCode":"238",
			"iso2Code":"CV",
			"iso3Code":"cpv",
			"name":"Cape Verde"
		},
		{
			"callingCode":"1",
			"iso2Code":"KY",
			"iso3Code":"cym",
			"name":"Cayman Islands"
		},
		{
			"callingCode":"56",
			"iso2Code":"CL",
			"iso3Code":"chl",
			"name":"Chile"
		},
		{
			"callingCode":"86",
			"iso2Code":"CN",
			"iso3Code":"chn",
			"name":"China"
		},
		{
			"callingCode":"61",
			"iso2Code":"CX",
			"iso3Code":"cxr",
			"name":"Christmas Island"
		},
		{
			"callingCode":"61",
			"iso2Code":"CC",
			"iso3Code":"cck",
			"name":"Cocos (Keeling) Islands"
		},
		{
			"callingCode":"57",
			"iso2Code":"CO",
			"iso3Code":"col",
			"name":"Colombia"
		},
		{
			"callingCode":"269",
			"iso2Code":"KM",
			"iso3Code":"com",
			"name":"Comoros"
		},
		{
			"callingCode":"682",
			"iso2Code":"CK",
			"iso3Code":"cok",
			"name":"Cook Islands"
		},
		{
			"callingCode":"506",
			"iso2Code":"CR",
			"iso3Code":"cri",
			"name":"Costa Rica"
		},
		{
			"callingCode":"225",
			"iso2Code":"CI",
			"iso3Code":"civ",
			"name":"Côte d'Ivoire"
		},
		{
			"callingCode":"385",
			"iso2Code":"HR",
			"iso3Code":"hrv",
			"name":"Croatia"
		},
		{
			"callingCode":"599",
			"iso2Code":"CW",
			"iso3Code":"cuw",
			"name":"Curaçao"
		},
		{
			"callingCode":"357",
			"iso2Code":"CY",
			"iso3Code":"cyp",
			"name":"Cyprus"
		},
		{
			"callingCode":"420",
			"iso2Code":"CZ",
			"iso3Code":"cze",
			"name":"Czech Republic"
		},
		{
			"callingCode":"45",
			"iso2Code":"DK",
			"iso3Code":"dnk",
			"name":"Denmark"
		},
		{
			"callingCode":"253",
			"iso2Code":"DJ",
			"iso3Code":"dji",
			"name":"Djibouti"
		},
		{
			"callingCode":"1",
			"iso2Code":"DM",
			"iso3Code":"dma",
			"name":"Dominica"
		},
		{
			"callingCode":"1",
			"iso2Code":"DO",
			"iso3Code":"dom",
			"name":"Dominican Republic"
		},
		{
			"callingCode":"593",
			"iso2Code":"EC",
			"iso3Code":"ecu",
			"name":"Ecuador"
		},
		{
			"callingCode":"20",
			"iso2Code":"EG",
			"iso3Code":"egy",
			"name":"Egypt"
		},
		{
			"callingCode":"503",
			"iso2Code":"SV",
			"iso3Code":"slv",
			"name":"El Salvador"
		},
		{
			"callingCode":"240",
			"iso2Code":"GQ",
			"iso3Code":"gnq",
			"name":"Equatorial Guinea"
		},
		{
			"callingCode":"372",
			"iso2Code":"EE",
			"iso3Code":"est",
			"name":"Estonia"
		},
		{
			"callingCode":"251",
			"iso2Code":"ET",
			"iso3Code":"eth",
			"name":"Ethiopia"
		},
		{
			"callingCode":"500",
			"iso2Code":"FK",
			"iso3Code":"flk",
			"name":"Falkland Islands"
		},
		{
			"callingCode":"298",
			"iso2Code":"FO",
			"iso3Code":"fro",
			"name":"Faroe Islands"
		},
		{
			"callingCode":"679",
			"iso2Code":"FJ",
			"iso3Code":"fji",
			"name":"Fiji"
		},
		{
			"callingCode":"358",
			"iso2Code":"FI",
			"iso3Code":"fin",
			"name":"Finland"
		},
		{
			"callingCode":"33",
			"iso2Code":"FR",
			"iso3Code":"fra",
			"name":"France"
		},
		{
			"callingCode":"594",
			"iso2Code":"GF",
			"iso3Code":"guf",
			"name":"French Guiana"
		},
		{
			"callingCode":"689",
			"iso2Code":"PF",
			"iso3Code":"pyf",
			"name":"French Polynesia"
		},
		{
			"callingCode":"262",
			"iso2Code":"TF",
			"iso3Code":"atf",
			"name":"French Southern Territories"
		},
		{
			"callingCode":"241",
			"iso2Code":"GA",
			"iso3Code":"gab",
			"name":"Gabon"
		},
		{
			"callingCode":"220",
			"iso2Code":"GM",
			"iso3Code":"gmb",
			"name":"Gambia"
		},
		{
			"callingCode":"995",
			"iso2Code":"GE",
			"iso3Code":"geo",
			"name":"Georgia"
		},
		{
			"callingCode":"49",
			"iso2Code":"DE",
			"iso3Code":"deu",
			"name":"Germany"
		},
		{
			"callingCode":"233",
			"iso2Code":"GH",
			"iso3Code":"gha",
			"name":"Ghana"
		},
		{
			"callingCode":"350",
			"iso2Code":"GI",
			"iso3Code":"gib",
			"name":"Gibraltar"
		},
		{
			"callingCode":"30",
			"iso2Code":"GR",
			"iso3Code":"grc",
			"name":"Greece"
		},
		{
			"callingCode":"299",
			"iso2Code":"GL",
			"iso3Code":"grl",
			"name":"Greenland"
		},
		{
			"callingCode":"1",
			"iso2Code":"GD",
			"iso3Code":"grd",
			"name":"Grenada"
		},
		{
			"callingCode":"590",
			"iso2Code":"GP",
			"iso3Code":"glp",
			"name":"Guadeloupe"
		},
		{
			"callingCode":"502",
			"iso2Code":"GT",
			"iso3Code":"gtm",
			"name":"Guatemala"
		},
		{
			"callingCode":"44",
			"iso2Code":"GG",
			"iso3Code":"ggy",
			"name":"Guernsey"
		},
		{
			"callingCode":"224",
			"iso2Code":"GN",
			"iso3Code":"gin",
			"name":"Guinea"
		},
		{
			"callingCode":"245",
			"iso2Code":"GW",
			"iso3Code":"gnb",
			"name":"Guinea-Bissau"
		},
		{
			"callingCode":"592",
			"iso2Code":"GY",
			"iso3Code":"guy",
			"name":"Guyana"
		},
		{
			"callingCode":"509",
			"iso2Code":"HT",
			"iso3Code":"hti",
			"name":"Haiti"
		},
		{
			"callingCode":"504",
			"iso2Code":"HN",
			"iso3Code":"hnd",
			"name":"Honduras"
		},
		{
			"callingCode":"852",
			"iso2Code":"HK",
			"iso3Code":"hkg",
			"name":"Hong Kong"
		},
		{
			"callingCode":"36",
			"iso2Code":"HU",
			"iso3Code":"hun",
			"name":"Hungary"
		},
		{
			"callingCode":"354",
			"iso2Code":"IS",
			"iso3Code":"isl",
			"name":"Iceland"
		},
		{
			"callingCode":"91",
			"iso2Code":"IN",
			"iso3Code":"ind",
			"name":"India"
		},
		{
			"callingCode":"62",
			"iso2Code":"ID",
			"iso3Code":"idn",
			"name":"Indonesia"
		},
		{
			"callingCode":"353",
			"iso2Code":"IE",
			"iso3Code":"irl",
			"name":"Ireland"
		},
		{
			"callingCode":"44",
			"iso2Code":"IM",
			"iso3Code":"imn",
			"name":"Isle of Man"
		},
		{
			"callingCode":"972",
			"iso2Code":"IL",
			"iso3Code":"isr",
			"name":"Israel"
		},
		{
			"callingCode":"39",
			"iso2Code":"IT",
			"iso3Code":"ita",
			"name":"Italy"
		},
		{
			"callingCode":"1",
			"iso2Code":"JM",
			"iso3Code":"jam",
			"name":"Jamaica"
		},
		{
			"callingCode":"81",
			"iso2Code":"JP",
			"iso3Code":"jpn",
			"name":"Japan"
		},
		{
			"callingCode":"44",
			"iso2Code":"JE",
			"iso3Code":"jey",
			"name":"Jersey"
		},
		{
			"callingCode":"962",
			"iso2Code":"JO",
			"iso3Code":"jor",
			"name":"Jordan"
		},
		{
			"callingCode":"7",
			"iso2Code":"KZ",
			"iso3Code":"kaz",
			"name":"Kazakhstan"
		},
		{
			"callingCode":"254",
			"iso2Code":"KE",
			"iso3Code":"ken",
			"name":"Kenya"
		},
		{
			"callingCode":"686",
			"iso2Code":"KI",
			"iso3Code":"kir",
			"name":"Kiribati"
		},
		{
			"callingCode":"383",
			"iso2Code":"XK",
			"iso3Code":"xkx",
			"name":"Kosovo, Republic of"
		},
		{
			"callingCode":"965",
			"iso2Code":"KW",
			"iso3Code":"kwt",
			"name":"Kuwait"
		},
		{
			"callingCode":"996",
			"iso2Code":"KG",
			"iso3Code":"kgz",
			"name":"Kyrgyzstan"
		},
		{
			"callingCode":"856",
			"iso2Code":"LA",
			"iso3Code":"lao",
			"name":"Laos"
		},
		{
			"callingCode":"371",
			"iso2Code":"LV",
			"iso3Code":"lva",
			"name":"Latvia"
		},
		{
			"callingCode":"961",
			"iso2Code":"LB",
			"iso3Code":"lbn",
			"name":"Lebanon"
		},
		{
			"callingCode":"266",
			"iso2Code":"LS",
			"iso3Code":"lso",
			"name":"Lesotho"
		},
		{
			"callingCode":"231",
			"iso2Code":"LR",
			"iso3Code":"lbr",
			"name":"Liberia"
		},
		{
			"callingCode":"423",
			"iso2Code":"LI",
			"iso3Code":"lie",
			"name":"Liechtenstein"
		},
		{
			"callingCode":"370",
			"iso2Code":"LT",
			"iso3Code":"ltu",
			"name":"Lithuania"
		},
		{
			"callingCode":"352",
			"iso2Code":"LU",
			"iso3Code":"lux",
			"name":"Luxembourg"
		},
		{
			"callingCode":"853",
			"iso2Code":"MO",
			"iso3Code":"mac",
			"name":"Macao"
		},
		{
			"callingCode":"389",
			"iso2Code":"MK",
			"iso3Code":"mkd",
			"name":"Macedonia, Former Yugoslav Republic of"
		},
		{
			"callingCode":"261",
			"iso2Code":"MG",
			"iso3Code":"mdg",
			"name":"Madagascar"
		},
		{
			"callingCode":"265",
			"iso2Code":"MW",
			"iso3Code":"mwi",
			"name":"Malawi"
		},
		{
			"callingCode":"60",
			"iso2Code":"MY",
			"iso3Code":"mys",
			"name":"Malaysia"
		},
		{
			"callingCode":"960",
			"iso2Code":"MV",
			"iso3Code":"mdv",
			"name":"Maldives"
		},
		{
			"callingCode":"223",
			"iso2Code":"ML",
			"iso3Code":"mli",
			"name":"Mali"
		},
		{
			"callingCode":"356",
			"iso2Code":"MT",
			"iso3Code":"mlt",
			"name":"Malta"
		},
		{
			"callingCode":"692",
			"iso2Code":"MH",
			"iso3Code":"mhl",
			"name":"Marshall Islands"
		},
		{
			"callingCode":"596",
			"iso2Code":"MQ",
			"iso3Code":"mtq",
			"name":"Martinique"
		},
		{
			"callingCode":"222",
			"iso2Code":"MR",
			"iso3Code":"mrt",
			"name":"Mauritania"
		},
		{
			"callingCode":"230",
			"iso2Code":"MU",
			"iso3Code":"mus",
			"name":"Mauritius"
		},
		{
			"callingCode":"262",
			"iso2Code":"YT",
			"iso3Code":"myt",
			"name":"Mayotte"
		},
		{
			"callingCode":"52",
			"iso2Code":"MX",
			"iso3Code":"mex",
			"name":"Mexico"
		},
		{
			"callingCode":"691",
			"iso2Code":"FM",
			"iso3Code":"fsm",
			"name":"Micronesia, Federated States of"
		},
		{
			"callingCode":"373",
			"iso2Code":"MD",
			"iso3Code":"mda",
			"name":"Moldova"
		},
		{
			"callingCode":"377",
			"iso2Code":"MC",
			"iso3Code":"mco",
			"name":"Monaco"
		},
		{
			"callingCode":"976",
			"iso2Code":"MN",
			"iso3Code":"mng",
			"name":"Mongolia"
		},
		{
			"callingCode":"382",
			"iso2Code":"ME",
			"iso3Code":"mne",
			"name":"Montenegro"
		},
		{
			"callingCode":"1",
			"iso2Code":"MS",
			"iso3Code":"msr",
			"name":"Montserrat"
		},
		{
			"callingCode":"212",
			"iso2Code":"MA",
			"iso3Code":"mar",
			"name":"Morocco"
		},
		{
			"callingCode":"258",
			"iso2Code":"MZ",
			"iso3Code":"moz",
			"name":"Mozambique"
		},
		{
			"callingCode":"95",
			"iso2Code":"MM",
			"iso3Code":"mmr",
			"name":"Myanmar"
		},
		{
			"callingCode":"264",
			"iso2Code":"NA",
			"iso3Code":"nam",
			"name":"Namibia"
		},
		{
			"callingCode":"674",
			"iso2Code":"NR",
			"iso3Code":"nru",
			"name":"Nauru"
		},
		{
			"callingCode":"977",
			"iso2Code":"NP",
			"iso3Code":"npl",
			"name":"Nepal"
		},
		{
			"callingCode":"31",
			"iso2Code":"NL",
			"iso3Code":"nld",
			"name":"Netherlands"
		},
		{
			"callingCode":"687",
			"iso2Code":"NC",
			"iso3Code":"ncl",
			"name":"New Caledonia"
		},
		{
			"callingCode":"64",
			"iso2Code":"NZ",
			"iso3Code":"nzl",
			"name":"New Zealand"
		},
		{
			"callingCode":"505",
			"iso2Code":"NI",
			"iso3Code":"nic",
			"name":"Nicaragua"
		},
		{
			"callingCode":"227",
			"iso2Code":"NE",
			"iso3Code":"ner",
			"name":"Niger"
		},
		{
			"callingCode":"234",
			"iso2Code":"NG",
			"iso3Code":"nga",
			"name":"Nigeria"
		},
		{
			"callingCode":"683",
			"iso2Code":"NU",
			"iso3Code":"niu",
			"name":"Niue"
		},
		{
			"callingCode":"672",
			"iso2Code":"NF",
			"iso3Code":"nfk",
			"name":"Norfolk Island"
		},
		{
			"callingCode":"47",
			"iso2Code":"NO",
			"iso3Code":"nor",
			"name":"Norway"
		},
		{
			"callingCode":"968",
			"iso2Code":"OM",
			"iso3Code":"omn",
			"name":"Oman"
		},
		{
			"callingCode":"92",
			"iso2Code":"PK",
			"iso3Code":"pak",
			"name":"Pakistan"
		},
		{
			"callingCode":"680",
			"iso2Code":"PW",
			"iso3Code":"plw",
			"name":"Palau"
		},
		{
			"callingCode":"970",
			"iso2Code":"PS",
			"iso3Code":"pse",
			"name":"Palestine"
		},
		{
			"callingCode":"507",
			"iso2Code":"PA",
			"iso3Code":"pan",
			"name":"Panama"
		},
		{
			"callingCode":"675",
			"iso2Code":"PG",
			"iso3Code":"png",
			"name":"Papua New Guinea"
		},
		{
			"callingCode":"595",
			"iso2Code":"PY",
			"iso3Code":"pry",
			"name":"Paraguay"
		},
		{
			"callingCode":"51",
			"iso2Code":"PE",
			"iso3Code":"per",
			"name":"Peru"
		},
		{
			"callingCode":"63",
			"iso2Code":"PH",
			"iso3Code":"phl",
			"name":"Philippines"
		},
		{
			"callingCode":"64",
			"iso2Code":"PN",
			"iso3Code":"pcn",
			"name":"Pitcairn Islands"
		},
		{
			"callingCode":"48",
			"iso2Code":"PL",
			"iso3Code":"pol",
			"name":"Poland"
		},
		{
			"callingCode":"351",
			"iso2Code":"PT",
			"iso3Code":"prt",
			"name":"Portugal"
		},
		{
			"callingCode":"1",
			"iso2Code":"PR",
			"iso3Code":"pri",
			"name":"Puerto Rico"
		},
		{
			"callingCode":"974",
			"iso2Code":"QA",
			"iso3Code":"qat",
			"name":"Qatar"
		},
		{
			"callingCode":"262",
			"iso2Code":"RE",
			"iso3Code":"reu",
			"name":"Réunion"
		},
		{
			"callingCode":"40",
			"iso2Code":"RO",
			"iso3Code":"rou",
			"name":"Romania"
		},
		{
			"callingCode":"250",
			"iso2Code":"RW",
			"iso3Code":"rwa",
			"name":"Rwanda"
		},
		{
			"callingCode":"590",
			"iso2Code":"BL",
			"iso3Code":"blm",
			"name":"Saint Barthélemy"
		},
		{
			"callingCode":"290",
			"iso2Code":"SH",
			"iso3Code":"shn",
			"name":"Saint Helena"
		},
		{
			"callingCode":"1",
			"iso2Code":"KN",
			"iso3Code":"kna",
			"name":"Saint Kitts and Nevis"
		},
		{
			"callingCode":"1",
			"iso2Code":"LC",
			"iso3Code":"lca",
			"name":"Saint Lucia"
		},
		{
			"callingCode":"599",
			"iso2Code":"MF",
			"iso3Code":"maf",
			"name":"Saint Martin (French part)"
		},
		{
			"callingCode":"508",
			"iso2Code":"PM",
			"iso3Code":"spm",
			"name":"Saint Pierre and Miquelon"
		},
		{
			"callingCode":"1",
			"iso2Code":"VC",
			"iso3Code":"vct",
			"name":"Saint Vincent and the Grenadines"
		},
		{
			"callingCode":"685",
			"iso2Code":"WS",
			"iso3Code":"wsm",
			"name":"Samoa"
		},
		{
			"callingCode":"378",
			"iso2Code":"SM",
			"iso3Code":"smr",
			"name":"San Marino"
		},
		{
			"callingCode":"239",
			"iso2Code":"ST",
			"iso3Code":"stp",
			"name":"Sao Tome and Principe"
		},
		{
			"callingCode":"966",
			"iso2Code":"SA",
			"iso3Code":"sau",
			"name":"Saudi Arabia"
		},
		{
			"callingCode":"221",
			"iso2Code":"SN",
			"iso3Code":"sen",
			"name":"Senegal"
		},
		{
			"callingCode":"381",
			"iso2Code":"RS",
			"iso3Code":"srb",
			"name":"Serbia"
		},
		{
			"callingCode":"248",
			"iso2Code":"SC",
			"iso3Code":"syc",
			"name":"Seychelles"
		},
		{
			"callingCode":"232",
			"iso2Code":"SL",
			"iso3Code":"sle",
			"name":"Sierra Leone"
		},
		{
			"callingCode":"65",
			"iso2Code":"SG",
			"iso3Code":"sgp",
			"name":"Singapore"
		},
		{
			"callingCode":"1",
			"iso2Code":"SX",
			"iso3Code":"sxm",
			"name":"Sint Maarten (Dutch part)"
		},
		{
			"callingCode":"421",
			"iso2Code":"SK",
			"iso3Code":"svk",
			"name":"Slovakia"
		},
		{
			"callingCode":"386",
			"iso2Code":"SI",
			"iso3Code":"svn",
			"name":"Slovenia"
		},
		{
			"callingCode":"677",
			"iso2Code":"SB",
			"iso3Code":"slb",
			"name":"Solomon Islands"
		},
		{
			"callingCode":"27",
			"iso2Code":"ZA",
			"iso3Code":"zaf",
			"name":"South Africa"
		},
		{
			"callingCode":"500",
			"iso2Code":"GS",
			"iso3Code":"sgs",
			"name":"South Georgia and the South Sandwich Islands"
		},
		{
			"callingCode":"82",
			"iso2Code":"KR",
			"iso3Code":"kor",
			"name":"South Korea"
		},
		{
			"callingCode":"34",
			"iso2Code":"ES",
			"iso3Code":"esp",
			"name":"Spain"
		},
		{
			"callingCode":"94",
			"iso2Code":"LK",
			"iso3Code":"lka",
			"name":"Sri Lanka"
		},
		{
			"callingCode":"597",
			"iso2Code":"SR",
			"iso3Code":"sur",
			"name":"Suriname"
		},
		{
			"callingCode":"268",
			"iso2Code":"SZ",
			"iso3Code":"swz",
			"name":"Swaziland"
		},
		{
			"callingCode":"46",
			"iso2Code":"SE",
			"iso3Code":"swe",
			"name":"Sweden"
		},
		{
			"callingCode":"41",
			"iso2Code":"CH",
			"iso3Code":"che",
			"name":"Switzerland"
		},
		{
			"callingCode":"886",
			"iso2Code":"TW",
			"iso3Code":"twn",
			"name":"Taiwan"
		},
		{
			"callingCode":"992",
			"iso2Code":"TJ",
			"iso3Code":"tjk",
			"name":"Tajikistan"
		},
		{
			"callingCode":"255",
			"iso2Code":"TZ",
			"iso3Code":"tza",
			"name":"Tanzania"
		},
		{
			"callingCode":"66",
			"iso2Code":"TH",
			"iso3Code":"tha",
			"name":"Thailand"
		},
		{
			"callingCode":"670",
			"iso2Code":"TL",
			"iso3Code":"tls",
			"name":"Timor-Leste"
		},
		{
			"callingCode":"228",
			"iso2Code":"TG",
			"iso3Code":"tgo",
			"name":"Togo"
		},
		{
			"callingCode":"690",
			"iso2Code":"TK",
			"iso3Code":"tkl",
			"name":"Tokelau"
		},
		{
			"callingCode":"676",
			"iso2Code":"TO",
			"iso3Code":"ton",
			"name":"Tonga"
		},
		{
			"callingCode":"1",
			"iso2Code":"TT",
			"iso3Code":"tto",
			"name":"Trinidad and Tobago"
		},
		{
			"callingCode":"216",
			"iso2Code":"TN",
			"iso3Code":"tun",
			"name":"Tunisia"
		},
		{
			"callingCode":"90",
			"iso2Code":"TR",
			"iso3Code":"tur",
			"name":"Turkey"
		},
		{
			"callingCode":"993",
			"iso2Code":"TM",
			"iso3Code":"tkm",
			"name":"Turkmenistan"
		},
		{
			"callingCode":"1",
			"iso2Code":"TC",
			"iso3Code":"tca",
			"name":"Turks and Caicos Islands"
		},
		{
			"callingCode":"688",
			"iso2Code":"TV",
			"iso3Code":"tuv",
			"name":"Tuvalu"
		},
		{
			"callingCode":"256",
			"iso2Code":"UG",
			"iso3Code":"uga",
			"name":"Uganda"
		},
		{
			"callingCode":"380",
			"iso2Code":"UA",
			"iso3Code":"ukr",
			"name":"Ukraine"
		},
		{
			"callingCode":"971",
			"iso2Code":"AE",
			"iso3Code":"are",
			"name":"United Arab Emirates"
		},
		{
			"callingCode":"44",
			"iso2Code":"GB",
			"iso3Code":"gbr",
			"name":"United Kingdom"
		},
		{
			"callingCode":"1",
			"iso2Code":"US",
			"iso3Code":"usa",
			"name":"United States"
		},
		{
			"callingCode":"598",
			"iso2Code":"UY",
			"iso3Code":"ury",
			"name":"Uruguay"
		},
		{
			"callingCode":"998",
			"iso2Code":"UZ",
			"iso3Code":"uzb",
			"name":"Uzbekistan"
		},
		{
			"callingCode":"678",
			"iso2Code":"VU",
			"iso3Code":"vut",
			"name":"Vanuatu"
		},
		{
			"callingCode":"39",
			"iso2Code":"VA",
			"iso3Code":"vat",
			"name":"Vatican City"
		},
		{
			"callingCode":"84",
			"iso2Code":"VN",
			"iso3Code":"vnm",
			"name":"Vietnam"
		},
		{
			"callingCode":"681",
			"iso2Code":"WF",
			"iso3Code":"wlf",
			"name":"Wallis and Futuna"
		},
		{
			"callingCode":"212",
			"iso2Code":"EH",
			"iso3Code":"esh",
			"name":"Western Sahara"
		},
		{
			"callingCode":"260",
			"iso2Code":"ZM",
			"iso3Code":"zmb",
			"name":"Zambia"
		},
		{
			"callingCode":"263",
			"iso2Code":"ZW",
			"iso3Code":"zwe",
			"name":"Zimbabwe"
		}
	]
}